import { ReactNode } from "react";
import Header from "./components/header";
import Main from "./components/main";
import type { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Contenedor>
      <Header />
      <Main>{children}</Main>
    </Contenedor>
  );
}

const Contenedor = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html lang="es">
      <body className="min-h-screen bg-gray-100">{children}</body>
    </html>
  );
};
