import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Theme from "@/app/theme";
import { Box } from "@mui/material";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Theme>
      <html lang="en">
        <Box component={"body"} style={{ backgroundColor: "black" }}>
          {children}
        </Box>
      </html>
    </Theme>
  );
}
