import { ReactNode } from "react";
import EncabezadoCompartidoPorTodoElSitio from "./components/encabezado-compartido-por-todo-el-sitio";
import type { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ContenedorBasicoParaTodoElSitio>
      <EncabezadoCompartidoPorTodoElSitio />
      <CuerpoPrincipalDelSitio>{children}</CuerpoPrincipalDelSitio>
    </ContenedorBasicoParaTodoElSitio>
  );
}

const ContenedorBasicoParaTodoElSitio = ({
  children,
}: Readonly<{ children: ReactNode }>) => {
  return (
    <html lang="es">
      <body className="min-h-screen bg-gray-100">{children}</body>
    </html>
  );
};

const CuerpoPrincipalDelSitio = ({ children }: { children: ReactNode }) => {
  return (
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {children}
    </main>
  );
};
